spring:
  application:
    name: apimanagement

  subservices:
    user-management:
      url: http://gromokoso-usermanagement:8080
    mcp-management:
      url: http://gromokoso-mcpmanagement:8080
    spec2tool:
      url: http://gromokoso-spec2tool:8080

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://gromokoso-keycloak:8080/realms/gromokoso/protocol/openid-connect/certs
    realm: swa2025

server:
  port: 8080

cors-allowed-origins: "http://localhost:8080"

logging:
  level:
    de.thm.apimanagement: DEBUG
    org.hibernate.sql: DEBUG
---
# Preconfigured profile for local testing
spring:
  config:
    activate:
      on-profile: dev
  subservices:
    user-management:
      url: http://gromokoso-usermanagement:8080
    mcp-management:
      url: http://gromokoso-mcpmanagement:8080
    spec2tool:
      url: http://gromokoso-spec2tool:8080

cors-allowed-origins: "http://localhost:5173"

---
# Preconfigured profile for deployment to the swa thm server
spring:
  config:
    activate:
      on-profile: prod
  subservices:
    user-management:
      url: https://zdh-swa-muenker.zdh.thm.de/gromokoso-usermanagement
    mcp-management:
      url: https://zdh-swa-muenker.zdh.thm.de/gromokoso-mcpmanagement
    spec2tool:
      url: https://zdh-swa-muenker.zdh.thm.de/gromokoso-spec2tool
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://zdh-swa-muenker.zdh.thm.de/keycloak/realms/swa2025
          jwk-set-uri: https://zdh-swa-muenker.zdh.thm.de/keycloak/realms/swa2025/protocol/openid-connect/certs

cors-allowed-origins: "https://zdh-swa-muenker.zdh.thm.de"